<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net48;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <NoWarn>$(NoWarn);NETSDK1206</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="Avalonia" Version="0.10.22" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.22" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.22" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.11" />
   </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Epoxy.Core.Avalonia\Epoxy.Core.Avalonia.csproj" />
    <ProjectReference Include="..\..\..\src\Epoxy.Avalonia\Epoxy.Avalonia.csproj" />
    <ProjectReference Include="..\EpoxyHello.Avalonia\EpoxyHello.Avalonia.csproj" />
  </ItemGroup>
</Project>
